# Generated by Django 3.2.3 on 2021-07-14 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affliction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AttackMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('attack_damage', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Boon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConditionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DamageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Statblock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('initiative_bonus', models.IntegerField()),
                ('armor_class', models.IntegerField()),
                ('hit_points', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('xp', models.IntegerField()),
                ('special_abilities', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('attack_methods', models.ManyToManyField(blank=True, related_name='attack_methods', to='battlebuddyapp.AttackMethod')),
                ('condition_immunities', models.ManyToManyField(blank=True, related_name='immune_species', to='battlebuddyapp.ConditionType')),
                ('damage_immunities', models.ManyToManyField(blank=True, related_name='immune_species', to='battlebuddyapp.DamageType')),
                ('damage_resistances', models.ManyToManyField(blank=True, related_name='resistant_species', to='battlebuddyapp.DamageType')),
                ('damage_vulnerabilities', models.ManyToManyField(blank=True, related_name='vulnerable_species', to='battlebuddyapp.DamageType')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('initiative', models.IntegerField()),
                ('health', models.IntegerField()),
                ('armour', models.IntegerField()),
                ('hpchange', models.IntegerField()),
                ('afflictions', models.ManyToManyField(blank=True, related_name='afflictied', to='battlebuddyapp.Affliction')),
                ('boons', models.ManyToManyField(blank=True, related_name='booned', to='battlebuddyapp.Boon')),
                ('faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='battlebuddyapp.faction')),
                ('statblock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='battlebuddyapp.statblock')),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('participants', models.ManyToManyField(related_name='battles', to='battlebuddyapp.Participant')),
            ],
        ),
    ]
