# Generated by Django 3.2.3 on 2021-07-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlebuddyapp', '0003_auto_20210707_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='hpchange',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
