# Generated by Django 3.2.3 on 2021-07-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlebuddyapp', '0004_participant_hpchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='initiativebonus',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
