# Generated by Django 3.2.3 on 2021-07-09 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battlebuddyapp', '0005_participant_initiativebonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='initiativebonus',
        ),
    ]
